server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: zumsim
    password: zumsim1103
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace